project:
  type: website

website:
  title: "Visual Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      
    right:
    - text: "Hands on Exercise"
      menu: 
        - text: "Hands-on Exercise 1 Introduction to Visual Analytics"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2 Designing Graphs to Enlighten"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html" 
        - text: "Hands-on Exercise 3 	Interactivity in Visual Analytics"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
        - text: "Hands-on Exercise 4 Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html"
        - text: "Hands-on Exercise 5 Network Data Visualisation and Analysis"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
        - text: "Hands-on Exercise 6 Visual Multivariate Analysis"
          href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
        - text: "Hands-on Exercise 7 Time Series Analysis"
          href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          

    - text: "In class Exercise"
      menu: 
        - text: "In class Exercise Basic ggplot"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
        - text: "In class Exercise Tableau public"
          href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
        - text: "In class Exercise QQ plot"
          href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
        - text: "In class Exercise Import JSON"
          href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          
    - text: "Take home Exercise"
      menu: 
        - text: "Take home Exercise 1 Demographic and spending patterns"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
        - text: "Take home Exercise 3"
          href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

